name: ollama-x-frontend-devcontainer

services:
  frontend:
    image: ghcr.io/yurzs/ollama-x-dev-frontend:latest
    pull_policy: always
    volumes:
      - ../..:/app:cached
      - frontend-node-modules:/app/frontend/node_modules
    command: sleep infinity
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
    expose:
      - 3000
    depends_on:
      - backend

  backend:
    image: ghcr.io/yurzs/ollama-x:latest
    pull_policy: always
    volumes:
      - ../..:/app:cached
      - backend-venv:/app/.venv
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017
      LANGFUSE_HOST: ${LF_HOST}
      LANGFUSE_PUBLIC_KEY: ${LF_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LF_SECRET_KEY}
      ENFORCE_MODEL: ${ENFORCE_MODEL}
      SENTRY_DSN: ${SENTRY_DSN}
      FORWARDED_ALLOW_IPS: ${FORWARDED_ALLOW_IPS}
      ANONYMOUS_ALLOWED: "False"
      ANONYMOUS_MODEL: ${ANONYMOUS_MODEL}
      USER_REGISTRATION_ENABLED: "False"
      PYTHONPATH: /app
    expose:
      - 8000
    depends_on:
      mongo:
        condition: service_healthy
    command: [
      "uvicorn", "ollama_x.app:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--reload",
    ]

  mongo:
    image: mongo:latest
    pull_policy: always
    volumes:
      - mongo-data:/data/db
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  mongo-data: {}
  frontend-node-modules: {}
  backend-venv: {}
