name: ollama-x

services:
  app:
    image: ghcr.io/yurzs/ollama-x:latest
    container_name: ${PROJECT_NAME}-app
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      LANGFUSE_HOST: ${LF_HOST}
      LANGFUSE_PUBLIC_KEY: ${LF_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LF_SECRET_KEY}
      ENFORCE_MODEL: ${ENFORCE_MODEL}
      SENTRY_DSN: ${SENTRY_DSN}
      FORWARDED_ALLOW_IPS: ${FORWARDED_ALLOW_IPS}
      ANONYMOUS_ALLOWED: ${ANONYMOUS_ALLOWED}
      ANONYMOUS_MODEL: ${ANONYMOUS_MODEL}
      USER_REGISTRATION_ENABLED: ${USER_REGISTRATION_ENABLED}
    volumes:
      - ~/.openapi_cli:/app/.openapi_cli/
    labels:
      - "traefik.http.routers.${PROJECT_NAME}-app.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}-app.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}-app.tls=true"
      - "traefik.http.services.${PROJECT_NAME}-app.loadbalancer.server.port=8000"
  scheduler:
    container_name: ${PROJECT_NAME}-scheduler
    image: ghcr.io/yurzs/ollama-x:latest
    depends_on:
      - app
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      SENTRY_DSN: ${SENTRY_DSN}
    command: ["ollama-x-scheduler"]
  mongo:
    container_name: ${PROJECT_NAME}-mongo
    image: mongo:latest
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    volumes:
      - ./database:/data/db
  traefik:
    container_name: ${PROJECT_NAME}-traefik
    image: traefik:v2.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    labels:
      - "traefik.http.routers.${PROJECT_NAME}-app.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}-app.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}-app.tls=true"
      - "traefik.http.services.${PROJECT_NAME}-app.loadbalancer.server.port=8000"
