OLLAMA = "ollama"
OPENAI = "openai"
CONTINUE = "continue"
API = "api"
CHAT = "chat"
COMPLETIONS = "completions"
EMBEDDINGS = "embeddings"
GENERATE = "generate"
REFACT = "refact"

ENDPOINT_CHAT = f"/{API}/{CHAT}"
ENDPOINT_COMPLETIONS = f"/{API}/{COMPLETIONS}"

OLLAMA_CHAT = f"/{OLLAMA}/{ENDPOINT_CHAT}"
OLLAMA_COMPLETIONS = f"/{OLLAMA}/{GENERATE}"
OLLAMA_EMBEDDINGS = f"/{OLLAMA}/{EMBEDDINGS}"
OLLAMA_TAGS = f"/{OLLAMA}/tags"
OLLAMA_SHOW = f"/{OLLAMA}/show"

# Legacy ollama endpoints
OLLAMA_LEGACY_CHAT = f"/{OLLAMA}/v1/{CHAT}"
OLLAMA_LEGACY_COMPLETIONS = f"/{OLLAMA}/v1/{CHAT}/{COMPLETIONS}"
OLLAMA_LEGACY_EMBEDDINGS = f"/v1/{EMBEDDINGS}"

OPENAI_CHAT = f"/{OPENAI}/{CHAT}"
OPENAI_CHAT_COMPLETIONS = f"/{OPENAI}/{CHAT}/{COMPLETIONS}"
OPENAI_EMBEDDINGS = f"/{OPENAI}/{EMBEDDINGS}"

# Legacy openai endpoints
OPENAI_LEGACY_CHAT = f"/{OPENAI}/v1/{CHAT}"
OPENAI_LEGACY_CHAT_COMPLETIONS = f"/{OPENAI}/v1/{CHAT}/{COMPLETIONS}"
OPENAI_LEGACY_EMBEDDINGS = f"/v1/{EMBEDDINGS}"

PREFIX_CONTINUE_PROJECT = f"/{CONTINUE}/project/{{project_id}}"

CONTINUE_ALL = f"/{CONTINUE}/all"
CONTINUE_ONE = f"/{CONTINUE}/one"
CONTINUE_CREATE = f"/{CONTINUE}/"
CONTINUE_PROJECT_JOIN = f"/{CONTINUE}/join/{{invite_id}}"
CONTINUE_SYNC_CONFIG = f"/{CONTINUE}/sync"
CONTINUE_PROJECT_RESET_INVITE = f"/{CONTINUE}/reset-invite/{{project_id}}"
CONTINUE_EDIT_MODELS = f"{PREFIX_CONTINUE_PROJECT}/models"
CONTINUE_EDIT_EMBEDDINGS = f"{PREFIX_CONTINUE_PROJECT}/embeddings"
CONTINUE_EDIT_TAB_AUTOCOMPLETE_MODEL = f"{PREFIX_CONTINUE_PROJECT}/tab-autocomplete-model"
CONTINUE_EDIT_TAB_AUTOCOMPLETE_OPTIONS = f"{PREFIX_CONTINUE_PROJECT}/tab-autocomplete-options"
CONTINUE_EDIT_CONTEXT_PROVIDERS = f"{PREFIX_CONTINUE_PROJECT}/context-providers"


REFACT_CAPS = f"/{REFACT}/refact-caps"
REFACT_CODING_ASSISTANT = f"/{REFACT}/coding_assistant_caps.json"
REFACT_TELEMETRY_BASIC = f"/{REFACT}/telemetry/basic"
REFACT_TELEMETRY_CORRECTED_SNIPPETS = f"/{REFACT}/telemetry/feedback"
