name: ollama-x-backend-devcontainer

services:
  backend:
    build:
      context: ../..
      dockerfile: .devcontainer/backend/Dockerfile
    volumes:
      - ../..:/app:cached
    command: [
      "uvicorn",
      "ollama_x.app:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--reload",
    ]
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017
      LANGFUSE_HOST: ${LF_HOST}
      LANGFUSE_PUBLIC_KEY: ${LF_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LF_SECRET_KEY}
      ENFORCE_MODEL: ${ENFORCE_MODEL}
      SENTRY_DSN: ${SENTRY_DSN}
      FORWARDED_ALLOW_IPS: ${FORWARDED_ALLOW_IPS}
      ANONYMOUS_ALLOWED: False
      ANONYMOUS_MODEL: ${ANONYMOUS_MODEL}
      USER_REGISTRATION_ENABLED: False
    expose:
      - 8000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  mongo-data: {}
