services:
  frontend:
    build:
      context: ..
      dockerfile: .devcontainer/frontend.Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ..
      dockerfile: .devcontainer/backend.Dockerfile
    volumes:
      - ..:/app:cached
    command: sleep infinity
    environment:
      - PYTHONPATH=/app
    ports:
      - 8000:8000
