services:
  frontend:
    image: ghcr.io/yurzs/ollama-x-dev-frontend:latest
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    image: ghcr.io/yurzs/ollama-x-dev-backend:latest
    volumes:
      - ..:/app:cached
    command: sleep infinity
    environment:
      - PYTHONPATH=/app
    ports:
      - 8000:8000
