name: ollama-x

services:
  app:
    container_name: ollama-x-app
    image: ollama-x:latest
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      LANGFUSE_HOST: ${LF_HOST}
      LANGFUSE_PUBLIC_KEY: ${LF_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LF_SECRET_KEY}
      ENFORCE_MODEL: ${ENFORCE_MODEL}
      USER_REGISTRATION_ENABLED: ${USER_REGISTRATION_ENABLED}
    volumes:
      - cli_creds:/app/.openapi_cli/
    labels:
      - "traefik.http.routers.ollama-x-app.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.ollama-x-app.entrypoints=websecure"
      - "traefik.http.routers.ollama-x-app.tls=true"
      - "traefik.http.services.ollama-x-app.loadbalancer.server.port=8000"
  scheduler:
    container_name: ollama-x-scheduler
    image: ollama-x:latest
    pull_policy: never
    depends_on:
      - app
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
    command: ["poetry", "run", "ollama-x-scheduler"]
  mongo:
    container_name: ollama-x-mongo
    image: mongo:latest
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    volumes:
      - database:/data/db
  traefik:
    container_name: ollama-x-traefik
    image: traefik:v2.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    labels:
      - "traefik.http.routers.ollama-x-app.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.ollama-x-app.entrypoints=websecure"
      - "traefik.http.routers.ollama-x-app.tls=true"
      - "traefik.http.services.ollama-x-app.loadbalancer.server.port=8000"

volumes:
  letsencrypt:
  database:
  cli_creds:
