name: Build and Publish Docker Image

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: |
            ghcr.io/yurzs/ollama-x:latest
            ghcr.io/yurzs/ollama-x:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push Debug Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          build-args: |
            debug=1
          tags: |
            ghcr.io/yurzs/ollama-x:latest-debug
            ghcr.io/yurzs/ollama-x:${{ github.ref_name }}-debug
          platforms: linux/amd64,linux/arm64
